title: Blog - DJ Darman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: DJ Darman # add your name
author-img: darman.jpg # add your photo
about-author: Liebes Brautpaar,   
nach 13 Jahren Erfahrung als Hochzeits-Dj möchte ich euch meine Erfahrung an euch weitergeben. An Eurem besonderen Tag ist es wichtig, dass alles perfekt abläuft. Mit diesem Blog werdet Ihr Anfängerfehler vermeiden. Bei weiteren Fragen könnt ihr mich auf meiner Homepage kontaktieren. Ich wünsche euch eine wunderschöne Hochzeit.
twitter: djdarman # add your Twitter handle
facebook: djdarman # add your Facebook handle
instagram: djdarman.de # add your Instagram handle
telegram: djdarman # add your Telegram handle
email: info@djdarman.de # add your Email address

# Disqus
discus-identifier: djdarman # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
